name: chimicapp
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  logger: ^1.1.0
  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.2.5
  flutter_launcher_icons: ^0.10.0
  permission_handler: ^10.0.0
  provider: ^6.0.3
  google_mobile_ads: ^2.0.1
  unicons: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  url_launcher: ^6.0.9

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/TempSplashScreen.png

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/iamges/ChimicApp.png"

flutter:
  uses-material-design: true
  
  assets:
    - ./assets/images/TempLogo.png
    - ./assets/images/ChimicApp.png

  fonts:
    - family: Nexa
      fonts:
        - asset: assets/fonts/NexaDemo-Bold.ttf
        - asset: assets/fonts/NexaDemo-Light.ttf
        - asset: assets/fonts/NexaTextDemo-Bold.ttf
        - asset: assets/fonts/NexaTextDemo-Bold.ttf
          weight: 300
  
