name: chimicapp
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter        
  intl: ^0.17.0
  logger: ^1.1.0
  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  url_launcher: ^6.0.9

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/TempSplashScreen.png

flutter:
  generate: true 
  uses-material-design: true
  
  assets:
    - ./assets/images/TempLogo.png

  fonts:
    - family: Nexa
      fonts:
        - asset: assets/fonts/NexaDemo-Bold.ttf
        - asset: assets/fonts/NexaDemo-Light.ttf
        - asset: assets/fonts/NexaTextDemo-Bold.ttf
        - asset: assets/fonts/NexaTextDemo-Bold.ttf
          weight: 300
  
