name: chimicapp
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  logger: ^1.1.0
  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.2.5
  flutter_launcher_icons: ^0.10.0
  permission_handler: ^10.0.0
  provider: ^6.0.3
  shared_preferences: ^2.0.15
  google_mobile_ads: ^2.0.1
  lazy_load_scrollview: ^1.3.0
  unicons: ^2.1.0
  dartpy: ^0.0.1+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  url_launcher: ^6.0.9

flutter_native_splash:
  color: "#292c83"
  image: assets/images/ChimicApp.png

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: assets/images/ChimicApp.png
  min_sdk_android: 21
  web:
    generate: true
    image_path: "path/to/image.png"

flutter:
  uses-material-design: true
  
  assets:
    - ./assets/images/ChimicApp.png

  fonts:
    - family: Nexa
      fonts:
        - asset: assets/fonts/NexaDemo-Bold.ttf
        - asset: assets/fonts/NexaDemo-Light.ttf
          weight: 300
  
